'use client';
import { useEffect, useMemo, useState } from 'react';
import { Login, ClubOperations, Promotions, Notifications, LiveDashboard } from '../components/Operations';
import { Bars3Icon, BuildingStorefrontIcon, CalendarDaysIcon, ClockIcon, HomeIcon, InformationCircleIcon, PhotoIcon, PlusIcon, Squares2X2Icon, XMarkIcon } from '../components/icons';

const SITE='https://lebistrotducoin.vercel.app';
const nav=[['dashboard','Tableau de bord',Squares2X2Icon],['daily','Menu du jour',CalendarDaysIcon],['menu','Carte',BuildingStorefrontIcon],['events','Événements',CalendarDaysIcon],['club','Club LBDC',InformationCircleIcon],['loyalty','Scanner fidélité',InformationCircleIcon],['promotions','Promotions',InformationCircleIcon],['notifications','Notifications',InformationCircleIcon],['club-settings','Réglages fidélité',InformationCircleIcon],['privatization','Privatisation',HomeIcon],['story','Notre histoire',InformationCircleIcon],['reviews','Avis et réseaux',InformationCircleIcon],['general','Informations et horaires',ClockIcon],['gallery','Galerie',PhotoIcon]];
const roleSections={fidelity:['loyalty'],employee:['dashboard','club','loyalty'],manager:['dashboard','daily','menu','events','club','loyalty','promotions','club-settings','privatization','story','reviews','general','gallery'],admin:nav.map(([id])=>id)};
const empty={general:{},pageTexts:{},daily:{formulas:[],starters:[],mains:[],desserts:[],suggestion:{}},menu:[],gallery:[],story:{paragraphs:[]},privatization:{photos:[]},events:[],reviews:{},socials:[],club:{title:'Club LBDC',intro:'',stampsRequired:10,reward:'La 11e formule offerte',conditions:'',enabled:true}};
const Field=({label,value,onChange,multi=false,type='text'})=><label className="field"><span>{label}</span>{multi?<textarea rows="4" value={value??''} onChange={e=>onChange(e.target.value)}/>:<input type={type} value={value??''} onChange={e=>onChange(e.target.value)}/>}</label>;
const Card=({children,className=''})=><section className={`card ${className}`}>{children}</section>;
const move=(arr,from,to)=>{if(to<0||to>=arr.length)return arr;const copy=[...arr];const [x]=copy.splice(from,1);copy.splice(to,0,x);return copy};

function OrderButtons({index,total,onMove}){return <div className="order-buttons"><button disabled={index===0} onClick={()=>onMove(index-1)}>↑ Monter</button><button disabled={index===total-1} onClick={()=>onMove(index+1)}>↓ Descendre</button></div>}
function ImagePicker({label,value,onChange,password,setStatus}){
 const [busy,setBusy]=useState(false);
 async function upload(file){if(!file)return;setBusy(true);setStatus('Envoi de la photo…');try{const fd=new FormData();fd.append('file',file);const r=await fetch('/api/upload',{method:'POST',headers:{'x-admin-password':password},body:fd});const j=await r.json();if(!r.ok)throw new Error(j.error);onChange(j.path);setStatus('Photo envoyée. Clique sur Publier pour enregistrer son emplacement.')}catch(e){setStatus(e.message)}finally{setBusy(false)}}
 return <div className="image-picker"><span>{label}</span>{value?<img src={value.startsWith('http')?value:`${SITE}${value}`} alt="Aperçu"/>:<div className="photo-placeholder"><PhotoIcon/><small>Aucune photo</small></div>}<label className="upload-button">{busy?'Envoi…':'Choisir une photo'}<input type="file" accept="image/*" onChange={e=>upload(e.target.files?.[0])} disabled={busy}/></label>{value&&<button className="danger-link" onClick={()=>onChange('')}>Retirer la photo</button>}</div>
}

export default function Home(){
 const [session,setSession]=useState(null);
 const [data,setData]=useState(empty),[sha,setSha]=useState(''),[section,setSection]=useState('dashboard'),[open,setOpen]=useState(false),[status,setStatus]=useState('Chargement…'),[busy,setBusy]=useState(false);
 useEffect(()=>{fetch('/api/auth/session').then(r=>r.json()).then(j=>{setSession(j);if(j.authenticated){setSection(j.role==='fidelity'?'loyalty':'dashboard');if(j.role!=='fidelity')load()}}).catch(()=>setSession({authenticated:false}))},[]);
 async function load(){setBusy(true);setStatus('Chargement du site…');try{const r=await fetch('/api/content',{headers:{}});const j=await r.json();if(!r.ok)throw new Error(j.error);setData({...empty,...j.content,club:{...empty.club,...j.content?.club}});setSha(j.sha);setStatus('Contenu réel du site chargé');}catch(e){setStatus(e.message)}finally{setBusy(false)}}
 async function save(){setBusy(true);setStatus('Publication en cours…');try{const r=await fetch('/api/content',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({content:data,sha})});const j=await r.json();if(!r.ok)throw new Error(j.error);setSha(j.sha);setStatus('Enregistré dans GitHub — Vercel republie le site');}catch(e){setStatus(e.message)}finally{setBusy(false)}}
 const patch=(key,val)=>setData(d=>({...d,[key]:val}));
 const count=useMemo(()=>data.menu.reduce((n,c)=>n+(c.items?.length||0),0),[data.menu]);
 const visibleNav=nav.filter(([id])=>(roleSections[session?.role]||[]).includes(id));
 const title=visibleNav.find(n=>n[0]===section)?.[1]||'Tableau de bord';
 const canPublish=session?.role==='manager'||session?.role==='admin';
 async function logout(){await fetch('/api/auth/logout',{method:'POST'});setSession({authenticated:false});setSection('dashboard')}
 if(session===null)return <main className="login-page"><div className="notice">Vérification de la session…</div></main>;
 if(!session.authenticated)return <Login onSuccess={current=>{setSession(current);setSection(current.role==='fidelity'?'loyalty':'dashboard');if(current.role!=='fidelity')load()}}/>;
 const updateDailyItem=(k,i,v)=>{const a=[...data.daily[k]];a[i]={...a[i],name:v};patch('daily',{...data.daily,[k]:a})};
 return <main className="app-shell"><aside className={`sidebar ${open?'open':''}`}><div className="brand"><div className="brand-mark">LBDC</div><div><strong>Administration</strong><span>{session.roleLabel}</span></div><button className="icon-button mobile-only" onClick={()=>setOpen(false)}><XMarkIcon/></button></div><nav>{visibleNav.map(([id,label,Icon])=><button key={id} className={section===id?'active':''} onClick={()=>{setSection(id);setOpen(false)}}><Icon/><span>{label}</span></button>)}</nav><div className="sidebar-footer"><div className="status-dot"/><div><strong>{session.username}</strong><span>{session.roleLabel}</span></div></div></aside>{open&&<button className="overlay" onClick={()=>setOpen(false)}/>}<section className="main-area"><header className="topbar"><button className="icon-button mobile-only" onClick={()=>setOpen(true)}><Bars3Icon/></button><div><p className="eyebrow">Le Bistrot Du Coin · {session.roleLabel}</p><h1>{title}</h1></div><div className="actions"><button className="secondary-button" onClick={logout}>Déconnexion</button>{canPublish&&<button className="primary-button" disabled={busy} onClick={save}>{busy?'Patiente…':'Publier'}</button>}</div></header><div className="content"><div className={`notice ${status.includes('Enregistré')||status.includes('chargé')?'success':''}`}>{status}</div>
 {section==='dashboard'&&<><div className="hero-card"><div><p className="eyebrow">Administration connectée</p><h2>Bonjour Thomas 👋</h2><p>Les contenus viennent directement du site public. Modifie, organise puis clique sur Publier.</p></div><HomeIcon/></div><LiveDashboard/><div className="stats-grid"><Card className="stat-card"><span>Produits</span><strong>{count}</strong><small>{data.menu.length} catégories</small></Card><Card className="stat-card"><span>Événements</span><strong>{data.events.length}</strong></Card><Card className="stat-card"><span>Photos</span><strong>{data.gallery.length}</strong></Card><Card className="stat-card"><span>Connexion</span><strong>{sha?'Active':'À vérifier'}</strong></Card></div></>}
 {section==='daily'&&<><Card><div className="section-heading"><h2>Formules</h2><button className="secondary-button" onClick={()=>patch('daily',{...data.daily,formulas:[...data.daily.formulas,{name:'Nouvelle formule',price:'',takeawayPrice:''}]})}><PlusIcon/>Ajouter</button></div><div className="item-list">{data.daily.formulas.map((f,i)=><div className="editor-box" key={i}><div className="form-grid"><Field label="Nom" value={f.name} onChange={v=>{const a=[...data.daily.formulas];a[i]={...f,name:v};patch('daily',{...data.daily,formulas:a})}}/><Field label="Prix sur place" value={f.price} onChange={v=>{const a=[...data.daily.formulas];a[i]={...f,price:v};patch('daily',{...data.daily,formulas:a})}}/><Field label="Prix à emporter" value={f.takeawayPrice} onChange={v=>{const a=[...data.daily.formulas];a[i]={...f,takeawayPrice:v};patch('daily',{...data.daily,formulas:a})}}/></div><button className="danger-link" onClick={()=>patch('daily',{...data.daily,formulas:data.daily.formulas.filter((_,x)=>x!==i)})}>Supprimer</button></div>)}</div></Card>{[['starters','Entrées'],['mains','Plats'],['desserts','Desserts']].map(([k,l])=><Card className="top-gap" key={k}><div className="section-heading"><h2>{l}</h2><button className="secondary-button" onClick={()=>patch('daily',{...data.daily,[k]:[...data.daily[k],{name:`Nouveau ${l.toLowerCase().slice(0,-1)}`}]})}><PlusIcon/>Ajouter</button></div><div className="item-list">{data.daily[k].map((x,i)=><div className="editor-row" key={i}><div className="grow"><Field label={`${l.slice(0,-1)} ${i+1}`} value={x.name} onChange={v=>updateDailyItem(k,i,v)}/></div><OrderButtons index={i} total={data.daily[k].length} onMove={to=>patch('daily',{...data.daily,[k]:move(data.daily[k],i,to)})}/><button className="danger-link" onClick={()=>patch('daily',{...data.daily,[k]:data.daily[k].filter((_,x)=>x!==i)})}>Supprimer</button></div>)}</div></Card>)}<Card className="top-gap"><h2>Suggestion</h2><div className="form-grid"><Field label="Nom" value={data.daily.suggestion.name} onChange={v=>patch('daily',{...data.daily,suggestion:{...data.daily.suggestion,name:v}})}/><Field label="Prix" value={data.daily.suggestion.price} onChange={v=>patch('daily',{...data.daily,suggestion:{...data.daily.suggestion,price:v}})}/><Field label="Description" value={data.daily.suggestion.description} onChange={v=>patch('daily',{...data.daily,suggestion:{...data.daily.suggestion,description:v}})}/><Field label="Texte supplément" value={data.daily.suggestionSupplementText} onChange={v=>patch('daily',{...data.daily,suggestionSupplementText:v})}/></div></Card></>}
 {section==='menu'&&<><Card><div className="section-heading"><h2>Carte complète</h2><button className="secondary-button" onClick={()=>patch('menu',[...data.menu,{category:'Nouvelle catégorie',items:[]}])}><PlusIcon/>Catégorie</button></div><Field label="Introduction" value={data.pageTexts.menuIntro} onChange={v=>patch('pageTexts',{...data.pageTexts,menuIntro:v})}/></Card>{data.menu.map((cat,ci)=><Card className="top-gap" key={ci}><div className="section-heading"><Field label="Catégorie" value={cat.category} onChange={v=>{const a=[...data.menu];a[ci]={...cat,category:v};patch('menu',a)}}/><div className="actions"><OrderButtons index={ci} total={data.menu.length} onMove={to=>patch('menu',move(data.menu,ci,to))}/><button className="secondary-button" onClick={()=>{const a=[...data.menu];a[ci]={...cat,items:[...(cat.items||[]),{name:'Nouveau produit',description:'',price:'',image:''}]};patch('menu',a)}}><PlusIcon/>Produit</button><button className="danger-link" onClick={()=>patch('menu',data.menu.filter((_,i)=>i!==ci))}>Supprimer catégorie</button></div></div><div className="item-list">{(cat.items||[]).map((it,ii)=><div className="editor-box" key={ii}><div className="form-grid"><Field label="Nom" value={it.name} onChange={v=>{const a=[...data.menu],items=[...cat.items];items[ii]={...it,name:v};a[ci]={...cat,items};patch('menu',a)}}/><Field label="Prix" value={it.price} onChange={v=>{const a=[...data.menu],items=[...cat.items];items[ii]={...it,price:v};a[ci]={...cat,items};patch('menu',a)}}/><Field label="Description" multi value={it.description} onChange={v=>{const a=[...data.menu],items=[...cat.items];items[ii]={...it,description:v};a[ci]={...cat,items};patch('menu',a)}}/><ImagePicker label="Photo du produit" value={it.image} password={''} setStatus={setStatus} onChange={v=>{const a=[...data.menu],items=[...cat.items];items[ii]={...it,image:v};a[ci]={...cat,items};patch('menu',a)}}/></div><div className="actions"><OrderButtons index={ii} total={cat.items.length} onMove={to=>{const a=[...data.menu];a[ci]={...cat,items:move(cat.items,ii,to)};patch('menu',a)}}/><button className="danger-link" onClick={()=>{const a=[...data.menu];a[ci]={...cat,items:cat.items.filter((_,i)=>i!==ii)};patch('menu',a)}}>Supprimer le produit</button></div></div>)}</div></Card>)}</>}
 {section==='events'&&<><Card><div className="section-heading"><h2>Événements</h2><button className="secondary-button" onClick={()=>patch('events',[...data.events,{title:'Nouvel événement',date:'',time:'',description:'',price:'',image:''}])}><PlusIcon/>Créer</button></div></Card>{data.events.map((e,i)=><Card className="top-gap" key={i}><div className="form-grid"><Field label="Titre" value={e.title} onChange={v=>{const a=[...data.events];a[i]={...e,title:v};patch('events',a)}}/><Field label="Date" value={e.date} onChange={v=>{const a=[...data.events];a[i]={...e,date:v};patch('events',a)}}/><Field label="Heure" value={e.time} onChange={v=>{const a=[...data.events];a[i]={...e,time:v};patch('events',a)}}/><Field label="Prix" value={e.price} onChange={v=>{const a=[...data.events];a[i]={...e,price:v};patch('events',a)}}/><Field label="Description" multi value={e.description} onChange={v=>{const a=[...data.events];a[i]={...e,description:v};patch('events',a)}}/><ImagePicker label="Photo" value={e.image} password={''} setStatus={setStatus} onChange={v=>{const a=[...data.events];a[i]={...e,image:v};patch('events',a)}}/></div><button className="danger-link" onClick={()=>patch('events',data.events.filter((_,x)=>x!==i))}>Supprimer</button></Card>)}</>}
 {section==='loyalty'&&<ClubOperations/>}
 {section==='promotions'&&<Promotions/>}
 {section==='notifications'&&<Notifications/>}
 {section==='club'&&<ClubOperations/>}
 {section==='club-settings'&&<Card><h2>Club LBDC</h2><div className="form-grid"><Field label="Titre" value={data.club.title} onChange={v=>patch('club',{...data.club,title:v})}/><Field label="Nombre d’achats nécessaires" type="number" value={data.club.stampsRequired} onChange={v=>patch('club',{...data.club,stampsRequired:Number(v)})}/><Field label="Récompense" value={data.club.reward} onChange={v=>patch('club',{...data.club,reward:v})}/><Field label="Introduction" multi value={data.club.intro} onChange={v=>patch('club',{...data.club,intro:v})}/><Field label="Conditions" multi value={data.club.conditions} onChange={v=>patch('club',{...data.club,conditions:v})}/></div><p className="muted">Les données du Club sont désormais enregistrées dans le fichier du site. L’affichage public du module sera raccordé dans la prochaine mise à jour du site.</p></Card>}
 {section==='privatization'&&<Card><h2>Privatisation</h2><div className="form-grid"><Field label="Titre" value={data.privatization.title} onChange={v=>patch('privatization',{...data.privatization,title:v})}/><Field label="Introduction" value={data.privatization.intro} onChange={v=>patch('privatization',{...data.privatization,intro:v})}/><Field label="Texte" multi value={data.privatization.text} onChange={v=>patch('privatization',{...data.privatization,text:v})}/></div></Card>}
 {section==='story'&&<Card><h2>Notre histoire</h2><div className="form-grid"><Field label="Petit titre" value={data.story.eyebrow} onChange={v=>patch('story',{...data.story,eyebrow:v})}/><Field label="Titre" value={data.story.title} onChange={v=>patch('story',{...data.story,title:v})}/><Field label="Introduction" multi value={data.story.intro} onChange={v=>patch('story',{...data.story,intro:v})}/><Field label="Citation" multi value={data.story.quote} onChange={v=>patch('story',{...data.story,quote:v})}/><ImagePicker label="Photo" value={data.story.image} password={''} setStatus={setStatus} onChange={v=>patch('story',{...data.story,image:v})}/></div><div className="top-gap"><div className="section-heading"><h3>Paragraphes</h3><button className="secondary-button" onClick={()=>patch('story',{...data.story,paragraphs:[...data.story.paragraphs,'Nouveau paragraphe']})}><PlusIcon/>Ajouter</button></div>{data.story.paragraphs.map((p,i)=><div className="editor-row" key={i}><div className="grow"><Field label={`Paragraphe ${i+1}`} multi value={p} onChange={v=>{const a=[...data.story.paragraphs];a[i]=v;patch('story',{...data.story,paragraphs:a})}}/></div><button className="danger-link" onClick={()=>patch('story',{...data.story,paragraphs:data.story.paragraphs.filter((_,x)=>x!==i)})}>Supprimer</button></div>)}</div></Card>}
 {section==='reviews'&&<><Card><h2>Avis</h2><div className="form-grid"><Field label="Titre" value={data.reviews.title} onChange={v=>patch('reviews',{...data.reviews,title:v})}/><Field label="Introduction" multi value={data.reviews.intro} onChange={v=>patch('reviews',{...data.reviews,intro:v})}/><Field label="Lien avis Google" value={data.reviews.googleReviewsUrl} onChange={v=>patch('reviews',{...data.reviews,googleReviewsUrl:v})}/><Field label="Lien écrire un avis" value={data.reviews.googleReviewWriteUrl} onChange={v=>patch('reviews',{...data.reviews,googleReviewWriteUrl:v})}/></div></Card><Card className="top-gap"><h2>Réseaux sociaux</h2>{data.socials.map((s,i)=><div className="form-grid editor-box top-gap" key={i}><Field label="Réseau" value={s.label} onChange={v=>{const a=[...data.socials];a[i]={...s,label:v};patch('socials',a)}}/><Field label="Lien" value={s.url} onChange={v=>{const a=[...data.socials];a[i]={...s,url:v};patch('socials',a)}}/></div>)}</Card></>}
 {section==='general'&&<Card><h2>Informations générales</h2><div className="form-grid"><Field label="Téléphone" value={data.general.phone} onChange={v=>patch('general',{...data.general,phone:v})}/><Field label="E-mail" value={data.general.email} onChange={v=>patch('general',{...data.general,email:v})}/><Field label="Adresse" multi value={data.general.address} onChange={v=>patch('general',{...data.general,address:v})}/><Field label="Horaires" multi value={data.general.hours} onChange={v=>patch('general',{...data.general,hours:v})}/><Field label="Message fermeture" multi value={data.general.closureMessage} onChange={v=>patch('general',{...data.general,closureMessage:v})}/></div></Card>}
 {section==='gallery'&&<><Card><div className="section-heading"><h2>Galerie</h2><button className="secondary-button" onClick={()=>patch('gallery',[...data.gallery,{src:'',alt:'',label:'Nouvelle photo'}])}><PlusIcon/>Ajouter</button></div></Card><div className="gallery-grid top-gap">{data.gallery.map((g,i)=><Card key={i}><ImagePicker label="Photo" value={g.src} password={''} setStatus={setStatus} onChange={v=>{const a=[...data.gallery];a[i]={...g,src:v};patch('gallery',a)}}/><div className="stack top-gap"><Field label="Titre" value={g.label} onChange={v=>{const a=[...data.gallery];a[i]={...g,label:v};patch('gallery',a)}}/><Field label="Texte alternatif" value={g.alt} onChange={v=>{const a=[...data.gallery];a[i]={...g,alt:v};patch('gallery',a)}}/></div><button className="danger-link top-gap" onClick={()=>patch('gallery',data.gallery.filter((_,x)=>x!==i))}>Supprimer</button></Card>)}</div></>}
 </div></section></main>
}
