'use client';
import {useEffect,useMemo,useState} from 'react';
import {translatableFields,translationFor} from '../lib/content-translations';
import clubDefaults from '../lib/club-editorial-defaults.json';
const groups={pageTexts:'Textes des pages',daily:'Menu du jour',menu:'Carte',events:'Événements',privatization:'Privatisation',story:'Notre histoire',galleryAlbums:'Albums',gallery:'Galerie',reviews:'Avis',general:'Informations',club:'Club LBDC',loyaltyProgram:'Fidélité',sectionPhotos:'Photos',heroImageAlt:'Photo d’accueil',catering:'Traiteur'};
const sections={'daily':'daily','menu':'menu','events':'events','privatization':'privatization','story':'story','gallery':'galleryAlbums','club':'club','club-settings':'loyaltyProgram','general':'general','texts':'pageTexts','reviews':'reviews','site-photos':'sectionPhotos'};
const labels={name:'Nom',description:'Description',category:'Catégorie',title:'Titre',intro:'Introduction',text:'Texte',label:'Légende',alt:'Texte alternatif',imageAlt:'Texte alternatif',paragraphs:'Paragraphe',conditions:'Conditions',clientText:'Texte client',reward:'Récompense',hours:'Horaires'};
export default function ContentTranslations({data,onChange,section}){
 const [language,setLanguage]=useState('fr'),[group,setGroup]=useState('pageTexts'),[query,setQuery]=useState(''),[missingOnly,setMissingOnly]=useState(false);
 useEffect(()=>{if(sections[section])setGroup(sections[section]);setQuery('')},[section]);
 const reference=useMemo(()=>({...data,club:{...clubDefaults,...Object.fromEntries(Object.entries(data.club||{}).filter(([,value])=>value!==''&&value!==undefined))}}),[data]);
 const fields=useMemo(()=>translatableFields(reference).filter(field=>field.path.split('.')[0]===group),[reference,group]);
 const visible=fields.filter(field=>(!query||field.source.toLocaleLowerCase('fr').includes(query.toLocaleLowerCase('fr')))&&(!missingOnly||language==='fr'||!translationFor(reference,field,language).trim()));
 const completed=language==='fr'?fields.length:fields.filter(field=>translationFor(reference,field,language).trim()).length;
 const update=(field,value)=>onChange(current=>({...current,translations:{...current.translations,[language]:{...current.translations?.[language],[field.path]:{source:field.source,value}}}}));
 function label(field){const keys=field.path.split('.');const key=keys.pop();const parent=keys.reduce((value,key)=>value?.[key],reference);const name=parent?.name||parent?.category||parent?.title;return [name,labels[key]||(Number.isInteger(Number(key))?'Texte '+(Number(key)+1):key)].filter(Boolean).join(' · ')}
 return <details className="card top-gap translations-panel"><summary style={{cursor:'pointer',fontWeight:700}}>Langues du site · traductions facultatives</summary><p className="muted top-gap">Les contenus actuels sont prétraduits. Choisissez une rubrique, puis une langue. Le français reste la référence ; un nouveau texte sans traduction reste affiché en français. Publiez pour enregistrer.</p><div className="form-grid"><label className="field"><span>Contenu à traduire</span><select value={group} onChange={e=>{setGroup(e.target.value);setQuery('')}}>{Object.entries(groups).map(([key,name])=><option key={key} value={key}>{name}</option>)}</select></label><label className="field"><span>Langue à renseigner</span><select value={language} onChange={e=>setLanguage(e.target.value)}>{[['fr','FR · référence'],['en','EN · English'],['es','ES · Español'],['pt','PT · Português'],['de','DE · Deutsch']].map(([key,name])=><option key={key} value={key}>{name}</option>)}</select></label></div><div className="form-grid top-gap"><label className="field"><span>Rechercher un plat, produit ou texte français</span><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nom, description…"/></label><div><p className="muted">{completed} / {fields.length} textes renseignés en {language.toUpperCase()}</p>{language!=='fr'&&<label><input type="checkbox" checked={missingOnly} onChange={e=>setMissingOnly(e.target.checked)}/> Afficher uniquement les traductions à compléter</label>}</div></div><div className="stack top-gap">{visible.map(field=>{const entry=data.translations?.[language]?.[field.path],stale=entry?.value&&entry.source?.trim()!==field.source.trim();return <label className="field editor-box" key={field.path}><span>{label(field)} · FR</span><p style={{whiteSpace:'pre-line',overflowWrap:'anywhere',margin:0}}>{field.source}</p>{language!=='fr'&&<><span>{language.toUpperCase()}{stale?' · Français modifié : traduction à revoir':''}</span><textarea rows={field.source.length>180?5:2} value={entry?.value??translationFor(reference,field,language)} placeholder="Facultatif : sinon, version française" onChange={e=>update(field,e.target.value)}/></>}</label>})}{!visible.length&&<p className="muted">{fields.length?'Aucun texte ne correspond à ce filtre.':'Aucun texte à traduire dans cette rubrique.'}</p>}</div></details>;
}
