'use client';
import {useMemo,useState} from 'react';
import {translatableFields} from '../lib/content-translations';
const groups={pageTexts:'Textes des pages',daily:'Menu du jour',menu:'Carte',events:'Événements',privatization:'Privatisation',story:'Notre histoire',galleryAlbums:'Albums',gallery:'Galerie',reviews:'Avis',general:'Informations',club:'Club LBDC',loyaltyProgram:'Fidélité',sectionPhotos:'Photos',heroImageAlt:'Photo d’accueil'};
export default function ContentTranslations({data,onChange}){
 const [language,setLanguage]=useState('fr'),[group,setGroup]=useState('pageTexts');
 const fields=useMemo(()=>translatableFields(data).filter(field=>field.path.split('.')[0]===group),[data,group]);
 const update=(field,value)=>onChange(current=>({...current,translations:{...current.translations,[language]:{...current.translations?.[language],[field.path]:{source:field.source,value}}}}));
 return <details className="card top-gap"><summary style={{cursor:'pointer',fontWeight:700}}>Langues du site · traductions facultatives</summary><p className="muted top-gap">Le français reste la référence. Sans traduction, le site affiche le français. Si le texte français change, sa traduction est à revoir. Cliquez sur Publier pour enregistrer.</p><div className="form-grid"><label className="field"><span>Langue à renseigner</span><select value={language} onChange={e=>setLanguage(e.target.value)}>{[['fr','Français · référence'],['en','English'],['es','Español'],['pt','Português'],['de','Deutsch']].map(([key,name])=><option key={key} value={key}>{name}</option>)}</select></label><label className="field"><span>Contenu à traduire</span><select value={group} onChange={e=>setGroup(e.target.value)}>{Object.entries(groups).map(([key,name])=><option key={key} value={key}>{name}</option>)}</select></label></div><div className="stack top-gap">{fields.map((field,index)=>{const entry=data.translations?.[language]?.[field.path],stale=entry?.value&&entry.source!==field.source;return <label className="field editor-box" key={field.path}><span>{groups[group]} · {index+1} · FR</span><p style={{whiteSpace:'pre-line',overflowWrap:'anywhere',margin:0}}>{field.source}</p>{language!=='fr'&&<><span>{language.toUpperCase()}{stale?' · Texte français modifié : traduction à revoir':''}</span><textarea rows={3} value={entry?.value||''} placeholder="Vide : version française" onChange={e=>update(field,e.target.value)}/></>}</label>})}{!fields.length&&<p className="muted">Aucun texte à traduire dans cette rubrique.</p>}</div></details>;
}
