'use client';
const groups=[['starters','Entrées','entrée'],['mains','Plats','plat'],['desserts','Desserts','dessert']];
const move=(items,from,to)=>{const next=[...items];next.splice(to,0,next.splice(from,1)[0]);return next};
export default function DailyMenuEditor({daily,onChange,Field,ImagePicker,setStatus}){
 const update=(key,index,values)=>onChange(current=>({...current,[key]:current[key].map((item,i)=>i===index?{...item,...values}:item)}));
 return <>{groups.map(([key,label,singular])=><section className="card top-gap" key={key} aria-label={label}>
  <h2>{label}</h2><div className="actions" style={{flexWrap:'wrap',marginBottom:16}}><button type="button" className="secondary-button" onClick={()=>onChange(current=>({...current,[key]:[...current[key],{name:'Nouveau '+singular}]}))}>Ajouter {singular==='entrée'?'une entrée':singular==='plat'?'un plat':'un dessert'}</button><span>{daily[key].length} élément(s)</span></div>
  <Field label={'Titre public — '+label} value={daily[key+'Title']} onChange={value=>onChange(current=>({...current,[key+'Title']:value}))}/>
  <div className="item-list">{daily[key].map((item,index)=><div className="editor-box" key={index} data-daily-item={key} style={{minWidth:0}}>
   <div className="actions" style={{flexWrap:'wrap',marginBottom:12}}><strong>{label} · {index+1}</strong><button type="button" className="secondary-button" disabled={index===0} aria-label={'Monter '+label+' '+(index+1)} onClick={()=>onChange(current=>({...current,[key]:move(current[key],index,index-1)}))}>Monter</button><button type="button" className="secondary-button" disabled={index===daily[key].length-1} aria-label={'Descendre '+label+' '+(index+1)} onClick={()=>onChange(current=>({...current,[key]:move(current[key],index,index+1)}))}>Descendre</button><button type="button" className="danger-link" aria-label={'Supprimer '+label+' '+(index+1)} onClick={()=>onChange(current=>({...current,[key]:current[key].filter((_,i)=>i!==index)}))}>Supprimer</button></div>
   <div className="stack"><Field label="Nom" value={item.name} onChange={name=>update(key,index,{name})}/><Field label="Description (facultative)" value={item.description} onChange={description=>update(key,index,{description})}/><Field label="Prix (facultatif)" value={item.price} onChange={price=>update(key,index,{price})}/><ImagePicker label={'Photo de '+(item.name||singular)+' (facultative)'} value={item.image} setStatus={setStatus} onChange={image=>update(key,index,{image})}/><Field label="Texte alternatif de la photo" value={item.imageAlt} onChange={imageAlt=>update(key,index,{imageAlt})}/></div>
  </div>)}</div>
 </section>)}<section className="card top-gap" aria-label="Suggestion du chef"><h2>Suggestion du chef</h2><div className="form-grid"><Field label="Nom de la suggestion" value={daily.suggestion.name} onChange={name=>onChange(current=>({...current,suggestion:{...current.suggestion,name}}))}/><Field label="Prix / supplément de la suggestion" value={daily.suggestion.price} onChange={price=>onChange(current=>({...current,suggestion:{...current.suggestion,price}}))}/><Field label="Description de la suggestion" value={daily.suggestion.description} onChange={description=>onChange(current=>({...current,suggestion:{...current.suggestion,description}}))}/><Field label="Texte global du supplément" value={daily.suggestionSupplementText} onChange={suggestionSupplementText=>onChange(current=>({...current,suggestionSupplementText}))}/></div></section></>;
}
