'use client';
import {useState,useRef,useEffect} from 'react';
export default function ProductLanguages({value,onChange,fields,legacy={}}){
 const [language,setLanguage]=useState('fr'),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const current=useRef(value),mounted=useRef(true);current.current=value;useEffect(()=>{mounted.current=true;return()=>{mounted.current=false}},[]);
 const entry=(lang,key)=>value.i18n?.[lang]?.[key]??legacy[lang]?.[key];
 const valid=(lang,key)=>{const e=entry(lang,key);return e?.source?.trim()===(value[key]||'').trim()?e.value||'':''};
 const update=(key,text)=>language==='fr'?onChange({[key]:text}):onChange({i18n:{...value.i18n,[language]:{...value.i18n?.[language],[key]:{source:value[key]||'',value:text}}}});
 async function generate(){setBusy(true);setMessage('');const snapshot=Object.fromEntries(fields.map(([key])=>[key,value[key]||'']));try{const r=await fetch('/api/product-translations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({fields:snapshot})});const d=await r.json();if(!r.ok)throw Error(d.error||'Traduction indisponible.');if(!mounted.current)return;const latest=current.current,i18n={...latest.i18n};for(const lang of ['en','es','pt','de']){i18n[lang]={...i18n[lang]};for(const [key,source]of Object.entries(snapshot)){if(latest[key]!==source)continue;const old=i18n[lang][key]??legacy[lang]?.[key];if(old?.value&&old.source===source)continue;if(d.translations?.[lang]?.[key])i18n[lang][key]={source,value:d.translations[lang][key]};}}onChange({i18n});setMessage('Traductions ajoutées. Vérifiez-les puis publiez. Les corrections existantes sont conservées.');}catch{if(mounted.current)setMessage('Traduction automatique indisponible. Vous pouvez saisir les langues ou publier le français.');}finally{if(mounted.current)setBusy(false)}}
 return <div style={{gridColumn:'1 / -1'}}><div className="actions" role="group" aria-label="Langue du contenu">{['fr','en','es','pt','de'].map(lang=><button type="button" key={lang} aria-pressed={language===lang} onClick={()=>setLanguage(lang)}>{lang.toUpperCase()}{lang!=='fr'&&fields.some(([key])=>value[key]&&!valid(lang,key))?' · à compléter':''}</button>)}</div>{fields.map(([key,label])=><label className="field" key={key}><span>{label} · {language.toUpperCase()}</span>{language!=='fr'&&<small>FR : {value[key]||'—'}{entry(language,key)?.value&&!valid(language,key)?' · Français modifié, traduction à revoir':''}</small>}{key==='description'||key==='subtitle'?<textarea rows={3} value={language==='fr'?value[key]||'':entry(language,key)?.value||''} onChange={e=>update(key,e.target.value)}/>:<input value={language==='fr'?value[key]||'':entry(language,key)?.value||''} onChange={e=>update(key,e.target.value)}/>}</label>)}<button type="button" disabled={busy||!fields.some(([key])=>value[key]?.trim())} onClick={generate}>{busy?'Traduction en cours…':'Générer les traductions manquantes'}</button><small> Facultatif · le français reste publiable. Les traductions suivent le produit lors des déplacements.</small><p role="status">{message}</p></div>
}
