'use client';
import {useState} from 'react';
import SectionPhoto from './SectionPhoto';
import DailyMenuView, {dailyThemes} from './DailyMenuView';
import LoyaltyProgramCard from './LoyaltyProgramCard';
import {normalizeLoyaltyProgram} from '../lib/loyalty-program';
const sections={home:'Accueil',today:'Menu du jour',menu:'Carte',gallery:'Galerie',events:'Événements',privatization:'Privatisation',catering:'Traiteur',story:'Notre histoire',reviews:'Avis & réseaux',club:'Club LBDC'};
export function SitePhotosEditor({data,onChange,ImagePicker,setStatus}){const [key,setKey]=useState('home'),[preview,setPreview]=useState(false);const photo=key==='home'?{image:data.heroImage,alt:data.heroImageAlt}:data.sectionPhotos?.[key]||{};const patch=values=>onChange(current=>key==='home'?({...current,...('image'in values?{heroImage:values.image}:{}),...('alt'in values?{heroImageAlt:values.alt}:{})}):({...current,sectionPhotos:{...current.sectionPhotos,[key]:{...current.sectionPhotos?.[key],...values}}}));return <section className="card"><h2>Photos du site</h2><label className="field"><span>Section à personnaliser</span><select value={key} onChange={e=>setKey(e.target.value)}>{Object.entries(sections).map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></label>{key==='catering'&&<p>La bannière Traiteur apparaît dans la page Privatisation.</p>}<ImagePicker key={key} label={'Photo — '+sections[key]} value={photo.image} onChange={image=>patch({image})} setStatus={setStatus}/><label className="field"><span>Texte alternatif de la bannière</span><input value={photo.alt||''} onChange={e=>patch({alt:e.target.value})}/></label><div className="actions"><button className="secondary-button" disabled={!photo.image} onClick={()=>patch({image:''})}>Supprimer la photo</button><button className="secondary-button" aria-expanded={preview} onClick={()=>setPreview(v=>!v)}>{preview?'Fermer la prévisualisation':'Prévisualiser la section'}</button></div>{preview&&<div aria-label="Aperçu de la section" style={{marginTop:20,border:'1px solid #ddd',overflow:'hidden'}}><SectionPhoto photo={photo}/><div style={{padding:24}}><h2>{sections[key]}</h2><p>{photo.image?'Aperçu de la photo avant publication.':'Aucune photo : aucun bloc image ne sera affiché.'}</p></div></div>}</section>}
export function DailyPreview({data,onThemeChange}) {
 const [open,setOpen]=useState(true),[mobile,setMobile]=useState(false);
 const theme=Object.hasOwn(dailyThemes,data.daily.theme)?data.daily.theme:'bistrot';
 return <section className="card top-gap">
  <h2>Ambiance du Menu du jour</h2><p className="muted">Choisissez une ambiance. L’aperçu se met à jour immédiatement, avant publication.</p>
  <label className="field"><span>Thème du Menu du jour</span><select value={theme} onChange={e=>{onThemeChange(e.target.value);setOpen(true)}}>{Object.entries(dailyThemes).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>
  <div className="actions" style={{flexWrap:'wrap',marginTop:16}}><button type="button" className="secondary-button" aria-expanded={open} onClick={()=>setOpen(v=>!v)}>{open?'Fermer la prévisualisation':'Prévisualiser le menu du jour'}</button><button type="button" className="secondary-button" aria-pressed={mobile} onClick={()=>{setMobile(v=>!v);setOpen(true)}}>{mobile?'Aperçu large':'Aperçu mobile · 390 px'}</button></div>
  {open&&<div aria-label="Prévisualisation du menu du jour" style={{marginTop:20}}><p className="muted">Rendu public · {dailyThemes[theme]} · Modifications non publiées</p><div style={{width:mobile?390:'100%',maxWidth:'100%',margin:'auto'}}><DailyMenuView daily={data.daily} introduction={data.pageTexts.todayIntro} phone={data.general.phone} phoneHref={data.general.phoneHref} photo={data.sectionPhotos?.today}/></div></div>}
 </section>;
}
export function LoyaltyProgramEditor({value,onChange}){const p=normalizeLoyaltyProgram(value),[preview,setPreview]=useState(false);const update=next=>onChange({...p,...next});return <section className="card"><h2>Programme de fidélité permanent</h2><p>Les tampons et l’historique sont conservés. Le seuil publié s’applique au solde courant.</p><div className="form-grid">{[['title','Titre de l’offre'],['description','Description de l’offre'],['reward','Récompense obtenue'],['clientText','Texte affiché au client']].map(([key,label])=><label className="field" key={key}><span>{label}</span><input value={p[key]} onChange={e=>update({[key]:e.target.value})}/></label>)}<label className="field"><span>Nombre d’achats nécessaires</span><input type="number" min="1" max="1000" step="1" value={value?.threshold??10} onChange={e=>onChange({...p,threshold:e.target.value===''?'':Number(e.target.value)})}/></label><label className="field"><span>Valeur de la récompense (€)</span><input type="number" min="0" step="0.01" value={value?.rewardValue??''} onChange={e=>update({rewardValue:e.target.value===''?null:Number(e.target.value)})}/><small>Vide : prix de la formule complète. Saisissez 0 pour une récompense sans valeur monétaire.</small></label></div><label><input type="checkbox" checked={p.enabled} onChange={e=>update({enabled:e.target.checked})}/> Activer le programme permanent</label><div className="actions"><button className="secondary-button" onClick={()=>setPreview(v=>!v)}>{preview?'Fermer l’aperçu':'Prévisualiser l’offre'}</button></div>{preview&&<LoyaltyProgramCard value={p}/>}</section>}
