import { randomBytes } from 'node:crypto';
import { sendMemberNotification } from './notifications';
import { birthdaySettingsTable, loyalty, sb, tables } from './supabase';

export const defaultBirthdaySettings={id:'default',enabled:true,title:'Joyeux anniversaire !',message:'Bon anniversaire [Prénom] 🎉\nPour fêter ça, Le Bistrot Du Coin vous offre un soft ou une bière pression 25 cl.\nPrésentez ce QR code lors de votre passage.\nOffre valable pendant 7 jours à compter de votre anniversaire, une seule utilisation.',gift:'Un soft ou une bière pression 25 cl offert(e)',durationDays:7,notify:true};
const parisParts=date=>Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Paris',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(date).filter(part=>part.type!=='literal').map(part=>[part.type,Number(part.value)]));
const validBirthday=value=>/^\d{4}-\d{2}-\d{2}$/.test(value||'')&&!Number.isNaN(new Date(`${value}T12:00:00Z`).getTime());
const personalize=(value,member)=>String(value||'').replaceAll('[Prénom]',member.first_name||'').trim();

export function upcomingBirthday(birthday,from=new Date()){
 if(!validBirthday(birthday))return null;
 const[birthYear,month,day]=birthday.split('-').map(Number),current=parisParts(from),today=Date.UTC(current.year,current.month-1,current.day);let year=current.year,target=Date.UTC(year,month-1,day);if(target<today){year+=1;target=Date.UTC(year,month-1,day)}
 return{year,date:new Date(target).toISOString().slice(0,10),daysUntil:Math.round((target-today)/86400000),age:year-birthYear};
}

export async function getBirthdaySettings(){const rows=await sb(`${birthdaySettingsTable}?id=eq.default&select=*&limit=1`),row=rows[0];return row?{id:'default',enabled:Boolean(row.enabled),title:row.title,message:row.message,gift:row.gift,durationDays:Number(row.duration_days)||7,notify:Boolean(row.notify)}:defaultBirthdaySettings}
export async function saveBirthdaySettings(input){const settings={...defaultBirthdaySettings,enabled:Boolean(input.enabled),title:String(input.title||'').trim(),message:String(input.message||'').trim(),gift:String(input.gift||'').trim(),durationDays:Math.min(30,Math.max(1,Number(input.durationDays)||7)),notify:Boolean(input.notify)};if(!settings.title||!settings.message||!settings.gift)throw new Error('Titre, message et cadeau obligatoires.');await sb(`${birthdaySettingsTable}?on_conflict=id`,{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:{id:'default',enabled:settings.enabled,title:settings.title,message:settings.message,gift:settings.gift,duration_days:settings.durationDays,notify:settings.notify,updated_at:new Date().toISOString()}});return settings}

export async function createBirthdayOffer(member,input={}){
 const occurrence=upcomingBirthday(member.birthday,input.now||new Date());if(!occurrence)throw new Error('Date de naissance manquante.');const year=input.year||occurrence.year,marker=`__LBDC_BIRTHDAY__:${member.id}:${year}`,existing=await sb(`${tables.promotions}?discount_label=eq.${encodeURIComponent(marker)}&select=*&limit=1`);if(existing[0]){const coupons=await sb(`${loyalty.coupons}?promotion_id=eq.${existing[0].id}&member_id=eq.${member.id}&select=*&limit=1`);return{created:false,promotion:existing[0],coupon:coupons[0]||null}}
 const start=input.startAt?new Date(input.startAt):new Date(),durationDays=Math.min(30,Math.max(1,Number(input.durationDays)||7)),end=input.endAt?new Date(input.endAt):new Date(start.getTime()+durationDays*86400000),rate=Math.min(100,Math.max(1,Number(input.discountRate)||100)),title=personalize(input.title||'Joyeux anniversaire !',member),message=personalize(input.message||defaultBirthdaySettings.message,member),gift=String(input.gift||defaultBirthdaySettings.gift).trim();if(!(end>start))throw new Error('Période de validité invalide.');
 const promotions=await sb(tables.promotions,{method:'POST',body:{title,description:message,start_at:start.toISOString(),end_at:end.toISOString(),active:false,coupon_enabled:false,discount_rate:rate,discount_label:marker,product_label:gift,created_at:new Date().toISOString()}}),promotion=promotions[0];if(!promotion)throw new Error('Création de la promotion impossible.');const coupons=await sb(`${loyalty.coupons}?on_conflict=promotion_id,member_id`,{method:'POST',headers:{Prefer:'resolution=ignore-duplicates,return=representation'},body:{promotion_id:promotion.id,member_id:member.id,token:randomBytes(24).toString('hex'),expires_at:end.toISOString(),discount_rate:rate,product_label:gift,original_amount_ttc:null}});return{created:true,promotion,coupon:coupons[0]||null};
}

export async function runAutomaticBirthdayOffers(now=new Date()){
 const settings=await getBirthdaySettings();if(!settings.enabled)return{enabled:false,eligible:0,created:0,notified:0};const members=await sb(`${tables.members}?birthday=not.is.null&select=id,first_name,last_name,email,birthday&limit=10000`),eligible=members.filter(member=>upcomingBirthday(member.birthday,now)?.daysUntil===0);let created=0,notified=0;for(const member of eligible){const result=await createBirthdayOffer(member,{now,year:upcomingBirthday(member.birthday,now).year,title:settings.title,message:settings.message,gift:settings.gift,durationDays:settings.durationDays,discountRate:100});if(!result.created)continue;created+=1;if(settings.notify){const sent=await sendMemberNotification(member.id,{title:`Joyeux anniversaire ${member.first_name||''} 🎂`.replace(/\s+🎂/,' 🎂'),body:'Votre cadeau anniversaire vous attend au Bistrot 🎁',url:'/club/espace',tag:`birthday-${member.id}-${upcomingBirthday(member.birthday,now).year}`});notified+=sent.sent}}
 return{enabled:true,eligible:eligible.length,created,notified};
}
